spring:
  application:
    name: KuimaKulak
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: postgres
    password: nurs123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  security:
    jwt:
      secret: bank_rest001100110011$$
  liquibase:
    change-log: db/migration.changelog/main-changelog.yaml
    enabled: true
  encryption:
    key: BankRestKey12345678iojerwoierhe9

server:
  port: 8282
springdoc:
  swagger-ui:
    enabled: true
